spring.application.name=boilerroom-labb1
spring.output.ansi.enabled=always
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Spring Vault
spring.config.import=vault://
spring.cloud.vault.host=127.0.0.1
spring.cloud.vault.port=8200
spring.cloud.vault.scheme=http
spring.cloud.vault.token=root
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=library-api
spring.cloud.compatibility-verifier.enabled=false
