spring.application.name=boilerroom-labb1
spring.output.ansi.enabled=always
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=create
spring.jpa.open-in-view=false
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Spring Vault
spring.config.import=vault://
spring.cloud.vault.host=127.0.0.1
spring.cloud.vault.port=8200
spring.cloud.vault.scheme=http
spring.cloud.vault.token=root
spring.cloud.vault.kv.enabled=true
spring.cloud.vault.kv.backend=secret
spring.cloud.vault.kv.default-context=library-api
spring.cloud.compatibility-verifier.enabled=false

# Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Resilience4j Circuit Breaker
resilience4j.circuitbreaker.instances.openLibrary.sliding-window-size=5
resilience4j.circuitbreaker.instances.openLibrary.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.openLibrary.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.openLibrary.permitted-number-of-calls-in-half-open-state=2

# Active URL
external.api.openlibrary.url=https://openlibrary.org/isbn/

# Used to test fallback (circuit breaker)
#external.api.openlibrary.url=https://this-does-not-exist.abc/isbn/
